[2024-04-14T10:02:59.013+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-14T10:02:59.055+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_world.hello_world scheduled__2024-04-13T00:00:00+00:00 [queued]>
[2024-04-14T10:02:59.067+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_world.hello_world scheduled__2024-04-13T00:00:00+00:00 [queued]>
[2024-04-14T10:02:59.068+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-14T10:02:59.086+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): hello_world> on 2024-04-13 00:00:00+00:00
[2024-04-14T10:02:59.094+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=288) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-14T10:02:59.097+0000] {standard_task_runner.py:63} INFO - Started process 289 to run task
[2024-04-14T10:02:59.097+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hello_world', 'hello_world', 'scheduled__2024-04-13T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/hello_world.py', '--cfg-path', '/tmp/tmpyxp0m1jz']
[2024-04-14T10:02:59.100+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask hello_world
[2024-04-14T10:02:59.155+0000] {task_command.py:426} INFO - Running <TaskInstance: hello_world.hello_world scheduled__2024-04-13T00:00:00+00:00 [running]> on host 6d95d7b460cc
[2024-04-14T10:02:59.272+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='alexeevkv' AIRFLOW_CTX_DAG_ID='hello_world' AIRFLOW_CTX_TASK_ID='hello_world' AIRFLOW_CTX_EXECUTION_DATE='2024-04-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-13T00:00:00+00:00'
[2024-04-14T10:02:59.273+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-14T10:02:59.334+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-14T10:02:59.337+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'hello world!']
[2024-04-14T10:02:59.355+0000] {subprocess.py:86} INFO - Output:
[2024-04-14T10:02:59.378+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: hello: command not found
[2024-04-14T10:02:59.379+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-04-14T10:02:59.383+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-14T10:02:59.397+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-04-14T10:02:59.407+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=hello_world, task_id=hello_world, execution_date=20240413T000000, start_date=20240414T100259, end_date=20240414T100259
[2024-04-14T10:02:59.430+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task hello_world (Bash command failed. The command returned a non-zero exit code 127.; 289)
[2024-04-14T10:02:59.476+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-14T10:02:59.506+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-14T10:02:59.512+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-04-14T14:36:21.574+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-14T14:36:21.615+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_world.hello_world scheduled__2024-04-13T00:00:00+00:00 [queued]>
[2024-04-14T14:36:21.628+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_world.hello_world scheduled__2024-04-13T00:00:00+00:00 [queued]>
[2024-04-14T14:36:21.629+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-14T14:36:21.649+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): hello_world> on 2024-04-13 00:00:00+00:00
[2024-04-14T14:36:21.659+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=84) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-04-14T14:36:21.661+0000] {standard_task_runner.py:63} INFO - Started process 85 to run task
[2024-04-14T14:36:21.662+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hello_world', 'hello_world', 'scheduled__2024-04-13T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/hello_world.py', '--cfg-path', '/tmp/tmpwcnfmfs0']
[2024-04-14T14:36:21.665+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask hello_world
[2024-04-14T14:36:21.724+0000] {task_command.py:426} INFO - Running <TaskInstance: hello_world.hello_world scheduled__2024-04-13T00:00:00+00:00 [running]> on host 8622fa8cbed1
[2024-04-14T14:36:21.848+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='alexeevkv' AIRFLOW_CTX_DAG_ID='hello_world' AIRFLOW_CTX_TASK_ID='hello_world' AIRFLOW_CTX_EXECUTION_DATE='2024-04-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-13T00:00:00+00:00'
[2024-04-14T14:36:21.850+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-14T14:36:21.913+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-14T14:36:21.916+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo hello world!']
[2024-04-14T14:36:21.931+0000] {subprocess.py:86} INFO - Output:
[2024-04-14T14:36:21.938+0000] {subprocess.py:93} INFO - hello world!
[2024-04-14T14:36:21.939+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-04-14T14:36:21.941+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-14T14:36:21.972+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=hello_world, task_id=hello_world, execution_date=20240413T000000, start_date=20240414T143621, end_date=20240414T143621
[2024-04-14T14:36:21.999+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-14T14:36:22.022+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-14T14:36:22.025+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
